name: Ejecutar Script con Playwright

on:
  schedule:
    # Corre de lunes a viernes a las 16:00 UTC (13:00 hs de Argentina)
    - cron: '31 13 * * 1-5'
      timezone: 'America/Argentina/Buenos_Aires'
  workflow_dispatch: # Botón para ejecución manual de prueba

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    # ACTUALIZADO: v4 -> v4.2.2 (Soporta Node 24 de forma nativa)
    - name: Descargar código del repositorio
      uses: actions/checkout@v4.2.2

    # ACTUALIZADO: v5 -> v5.4.0 (Soporta Node 24 de forma nativa)
    - name: Configurar Python
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.10'

    - name: Instalar librerías
      run: |
        python -m pip install --upgrade pip
        pip install requests playwright

    - name: Instalar Navegadores de Playwright y dependencias
      run: |
        python -m playwright install chromium --with-deps

    - name: Adaptar código para entorno en la nube (Linux / Headless)
      run: |
        # Cambia headless=False por headless=True para que corra en la nube sin pantalla
        sed -i 's/headless=False/headless=True/g' main.py
        
        # Redirecciona la carpeta de descargas de Windows al directorio local de la máquina virtual
        sed -i 's|carpeta_descargas_windows = os.path.join(os.path.expanduser("~"), "Downloads")|carpeta_descargas_windows = os.getcwd()|g' main.py

    - name: Ejecutar el script de Python
      env:
        # Mapeamos los secretos guardados en GitHub hacia las variables que leerá Python
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
      
    - name: Subir planilla PDF como artefacto descargable
      uses: actions/upload-artifact@v4
      with:
        name: Planilla-Asistencia
        path: |
          *.pdf
        retention-days: 5
